### ISSUE TITLE
Setting to have chat start from bottom and scroll up

### ISSUE THREAD

**Issue by benbarbour** [mouse0270/always-chat#3]
This would mirror the normal chat bar, making it a bit easier to jump between the two when desired. Also, it would prevent the messages from being hidden by modules like Visual Active Effects or Dfred's Effects Panel.

**Comment by mouse0270** [comment]
Do you mean the bottom of the sidebar? I could add a setting to position the chat in the top-left, top-right, bottom-left or bottom-right. 

Is that what you are looking for?

**Comment by benbarbour** [comment]
Yes, sorry for being unclear. I mean to position it in the bottom right, with the newest messages on the bottom the way the chat sidebar organizes things.

**Comment by mouse0270** [comment]
I'd just drop in two settings:
- Position and let you choose `top left`, `top right`, `bottom left` or `bottom right`
- Direction `Newest on Top` or `Newest on Bottom`

I believe these two options should accomplish any layout users may want, even if I think most people would only choose `top right` or `bottom right` lol

**Comment by mouse0270** [comment]
Should be resolved in version 1.0.2 https://github.com/mouse0270/always-chat/releases/tag/1.0.2
