### ISSUE TITLE
Allow right click context menu on floating chats

### ISSUE THREAD

**Issue by benbarbour** [mouse0270/always-chat#4]
Useful to use the "Apply Damage" feature of core while on the combat tracker tab.

**Comment by mouse0270** [comment]
This should work but it appears there is some issue with it being cut off. I will see what I can do to resolve these css conflicts.

**Comment by mouse0270** [comment]
Should be resolved in version 1.0.2 https://github.com/mouse0270/always-chat/releases/tag/1.0.2
