### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/always-chat#7]
Please, update to v11

**Comment by brunocalado** [comment]
![image](https://github.com/mouse0270/always-chat/assets/4999783/68c5034b-d7d4-4b46-8cf0-2c4347e98493)

**Comment by mouse0270** [comment]
It should be available within the next 24-36 hours

**Comment by mouse0270** [comment]
Sorry about the delay. I got distracted making Kasper... But you should be able to install and use it on v11 now
